# Generated by Django 6.0.5 on 2026-06-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_hora_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de início'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_hora_termino',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de término'),
        ),
    ]
