# Generated by Django 6.0.5 on 2026-06-01 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_data_hora_inicio_tarefa_data_hora_termino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='excluida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluída em'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='excluida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_excluidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
