# Generated by Django 6.0.5 on 2026-06-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0006_voluntario'),
        ('tarefas', '0003_tarefa_excluida_em_tarefa_excluida_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='cabos',
            field=models.ManyToManyField(blank=True, related_name='tarefas', to='liderancas.caboeleitoral', verbose_name='Cabos Eleitorais'),
        ),
    ]
