# Generated by Django 6.0.5 on 2026-06-01 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_comentario_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='tarefas/anexos/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='tarefas.comentario')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
        ),
    ]
