# Generated by Django 6.0.5 on 2026-06-01 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_cor_field'),
        ('tarefas', '0007_anexo_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='compromisso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='agenda.compromisso', verbose_name='Compromisso vinculado'),
        ),
    ]
