# Generated by Django 6.0.5 on 2026-06-13 21:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0013_interacaolog_egresso_interacaolog_lassberg'),
        ('tarefas', '0008_add_compromisso_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro_linha', models.CharField(blank=True, max_length=200, verbose_name='Bairro / Linha')),
                ('descricao', models.CharField(max_length=300, verbose_name='Demanda')),
                ('solicitante', models.CharField(blank=True, max_length=200, verbose_name='Quem pediu')),
                ('responsavel', models.CharField(blank=True, max_length=200, verbose_name='Responsável pela entrega')),
                ('status', models.CharField(choices=[('registrada', 'Registrada'), ('em_andamento', 'Em andamento'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], db_index=True, default='registrada', max_length=15)),
                ('data_registro', models.DateField(default=django.utils.timezone.localdate)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promessas_cadastradas', to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promessas', to='liderancas.cidade')),
            ],
            options={
                'verbose_name': 'Promessa / Demanda do Eleitor',
                'verbose_name_plural': 'Promessas / Demandas do Eleitor',
                'ordering': ['-data_registro'],
            },
        ),
    ]
