# Generated by Django 6.0.5 on 2026-06-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0018_remove_interacaolog_apoiador_and_more'),
        ('tarefas', '0009_promessa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='cabos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'papel': 'cabo'}, related_name='tarefas', to='liderancas.lideranca', verbose_name='Cabos Eleitorais'),
        ),
    ]
