# Generated by Django 6.0.5 on 2026-06-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Depende só da criação de Lideranca (0016), NÃO da 0018: este re-aponte
        # de Tarefa.cabos → lideranca precisa rodar ANTES da 0018 deletar
        # caboeleitoral, senão o estado fica com referência pendurada (deploy crasha).
        ('liderancas', '0016_lideranca'),
        ('tarefas', '0009_promessa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='cabos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'papel': 'cabo'}, related_name='tarefas', to='liderancas.lideranca', verbose_name='Cabos Eleitorais'),
        ),
    ]
