# Generated by Django 6.0.5 on 2026-07-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0012_alter_tarefa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='link_reuniao',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link da reunião'),
        ),
    ]
