# Generated by Django 6.0.5 on 2026-06-15 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0006_compromisso_aliados_evento_aliados'),
        ('liderancas', '0015_cidade_adversario_nome_cidade_adversario_partido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('territorio', 'Território'), ('relacionamento', 'Relacionamento'), ('concorrencia', 'Concorrência'), ('agenda', 'Agenda'), ('demanda', 'Demanda')], db_index=True, max_length=20)),
                ('titulo', models.CharField(max_length=160)),
                ('justificativa', models.TextField(blank=True)),
                ('acao_sugerida', models.CharField(blank=True, max_length=120)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], db_index=True, default='media', max_length=6)),
                ('fonte', models.CharField(choices=[('regra', 'Determinístico'), ('agente', 'Agente IA')], default='regra', max_length=10)),
                ('agente', models.CharField(blank=True, max_length=40)),
                ('evidencia', models.JSONField(blank=True, default=dict)),
                ('dedup_key', models.CharField(db_index=True, max_length=120)),
                ('ciclo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('nova', 'Nova'), ('vista', 'Vista'), ('em_andamento', 'Em andamento'), ('agendada', 'Agendada'), ('descartada', 'Descartada'), ('concluida', 'Concluída'), ('expirada', 'Expirada')], db_index=True, default='nova', max_length=14)),
                ('motivo_descarte', models.CharField(blank=True, max_length=200)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('vista_em', models.DateTimeField(blank=True, null=True)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('atribuida_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='liderancas.cidade')),
                ('compromisso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='agenda.compromisso')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-score', '-criada_em'],
                'indexes': [models.Index(fields=['status', 'tipo', 'prioridade'], name='oportunidad_status_4283df_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['nova', 'vista', 'em_andamento'])), fields=('dedup_key',), name='uniq_oportunidade_viva')],
            },
        ),
    ]
