# Generated by Django 6.0.5 on 2026-06-02 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liderancas', '0009_cidade_latitude_cidade_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(choices=[(2018, '2018'), (2022, '2022'), (2026, '2026')])),
                ('tipo', models.CharField(choices=[('deputado_federal', 'Deputado Federal'), ('deputado_estadual', 'Deputado Estadual'), ('senador', 'Senador'), ('governador', 'Governador'), ('presidente', 'Presidente'), ('prefeito', 'Prefeito'), ('vereador', 'Vereador')], max_length=20)),
                ('turno', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Eleição',
                'verbose_name_plural': 'Eleições',
                'unique_together': {('ano', 'tipo', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato_nome', models.CharField(max_length=255)),
                ('candidato_numero', models.CharField(max_length=10)),
                ('partido', models.CharField(max_length=150)),
                ('votos', models.IntegerField(default=0)),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('eleito', models.BooleanField(default=False)),
                ('is_sorgatto', models.BooleanField(default=False)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_eleicao', to='liderancas.cidade')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='mapa.eleicao')),
            ],
            options={
                'verbose_name': 'Resultado por Candidato',
                'verbose_name_plural': 'Resultados por Candidato',
                'indexes': [models.Index(fields=['eleicao', 'cidade'], name='mapa_result_eleicao_ff26cc_idx'), models.Index(fields=['is_sorgatto'], name='mapa_result_is_sorg_d56bb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResultadoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato_nome', models.CharField(max_length=255)),
                ('candidato_numero', models.CharField(max_length=10)),
                ('partido', models.CharField(max_length=150)),
                ('zona', models.CharField(max_length=10)),
                ('votos', models.IntegerField(default=0)),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_sorgatto', models.BooleanField(default=False)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_zona', to='liderancas.cidade')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_zona', to='mapa.eleicao')),
            ],
            options={
                'verbose_name': 'Resultado por Zona',
                'verbose_name_plural': 'Resultados por Zona',
                'indexes': [models.Index(fields=['eleicao', 'cidade', 'zona'], name='mapa_result_eleicao_46d728_idx')],
            },
        ),
    ]
