# Generated by Django 6.0.5 on 2026-06-14 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0015_cidade_adversario_nome_cidade_adversario_partido_and_more'),
        ('mapa', '0003_add_demograficos_indicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliadoChapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('termos_busca', models.CharField(help_text='Termos que devem aparecer no nome do candidato em 2022 (ex.: "CAROL TONI").', max_length=120)),
                ('cargo_2026', models.CharField(blank=True, max_length=60, verbose_name='Cargo em 2026')),
                ('cor', models.CharField(default='#2563eb', max_length=7)),
                ('ativo', models.BooleanField(default=True, help_text='Marcado no mapa de Transferência.')),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Aliado de Chapa',
                'verbose_name_plural': 'Aliados de Chapa',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AgendaAliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_aliados', to='liderancas.cidade')),
                ('aliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='mapa.aliadochapa')),
            ],
            options={
                'verbose_name': 'Agenda de Aliado',
                'verbose_name_plural': 'Agendas de Aliados',
                'ordering': ['data'],
            },
        ),
    ]
