# Generated by Django 6.0.5 on 2026-06-14 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0004_aliadochapa_agendaaliado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgendaAliado',
        ),
    ]
