# Generated by Django 6.0.5 on 2026-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0005_delete_agendaaliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliadochapa',
            name='candidato_numero',
            field=models.CharField(blank=True, help_text='Número na urna em 2022. Quando preenchido, o cruzamento de votos é exato.', max_length=10),
        ),
        migrations.AddField(
            model_name='aliadochapa',
            name='cargo_2022',
            field=models.CharField(blank=True, help_text='governador, senador, deputado_federal ou deputado_estadual.', max_length=30, verbose_name='Cargo em 2022'),
        ),
        migrations.AddField(
            model_name='aliadochapa',
            name='partido',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
