# Generated by Django 6.0.5 on 2026-05-30 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liderancas', '0002_apoiador_atualizado_por_caboeleitoral_atualizado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Início')),
                ('data_hora_fim', models.DateTimeField(verbose_name='Fim')),
                ('tipo', models.CharField(choices=[('reuniao', 'Reunião'), ('evento', 'Evento'), ('visita', 'Visita'), ('comicio', 'Comício'), ('entrevista', 'Entrevista'), ('viagem', 'Viagem'), ('pessoal', 'Pessoal')], max_length=15)),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('contato_local_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome do Contato Local')),
                ('contato_local_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Contato')),
                ('participantes', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], default='pendente', max_length=15)),
                ('cor', models.CharField(blank=True, choices=[('#002776', 'Azul'), ('#dc2626', 'Vermelho'), ('#047857', 'Verde'), ('#d97706', 'Amarelo'), ('#7c3aed', 'Roxo'), ('#6b7280', 'Cinza')], default='#002776', max_length=7)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromissos', to='liderancas.cidade')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromissos', to='liderancas.regiao', verbose_name='Região')),
            ],
            options={
                'verbose_name': 'Compromisso',
                'verbose_name_plural': 'Compromissos',
                'ordering': ['data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('motorista', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='planejado', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiros_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiros_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roteiros', to='liderancas.regiao', verbose_name='Região Principal')),
            ],
            options={
                'verbose_name': 'Roteiro',
                'verbose_name_plural': 'Roteiros',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RoteiroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('observacao_ponto', models.TextField(blank=True, verbose_name='Observação do Ponto')),
                ('compromisso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roteiro_pontos', to='agenda.compromisso')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='agenda.roteiro')),
            ],
            options={
                'verbose_name': 'Ponto do Roteiro',
                'verbose_name_plural': 'Pontos do Roteiro',
                'ordering': ['ordem'],
                'unique_together': {('roteiro', 'compromisso')},
            },
        ),
    ]
