# Generated by Django 6.0.5 on 2026-05-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromisso',
            name='cor',
        ),
    ]
