# Generated by Django 6.0.5 on 2026-06-02 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_cor_field'),
        ('liderancas', '0007_add_endereco_voluntario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome do Evento')),
                ('tipo', models.CharField(choices=[('inauguracao', 'Inauguração'), ('festa', 'Festa'), ('feira', 'Feira'), ('encontro', 'Encontro'), ('solenidade', 'Solenidade'), ('audiencia', 'Audiência Pública'), ('debate', 'Debate'), ('palestra', 'Palestra'), ('show', 'Show / Apresentação'), ('esportivo', 'Evento Esportivo'), ('religioso', 'Evento Religioso'), ('outro', 'Outro')], max_length=20)),
                ('data', models.DateField(verbose_name='Data')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='Horário Início')),
                ('horario_fim', models.TimeField(blank=True, null=True, verbose_name='Horário Fim')),
                ('local', models.CharField(blank=True, max_length=300, verbose_name='Local / Endereço')),
                ('publico_estimado', models.PositiveIntegerField(blank=True, null=True, verbose_name='Público Estimado')),
                ('relevancia', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Relevância Política')),
                ('status', models.CharField(choices=[('identificado', 'Identificado'), ('avaliando', 'Avaliando'), ('confirmado', 'Presença Confirmada'), ('descartado', 'Descartado'), ('participou', 'Participou')], default='identificado', max_length=15)),
                ('observacoes', models.TextField(blank=True, help_text='Quem organiza, adversários confirmados, oportunidade de fala, etc.', verbose_name='Observações')),
                ('resultado', models.TextField(blank=True, help_text='Preencher após a participação.', verbose_name='Resultado / Avaliação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='liderancas.cidade')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data', 'horario_inicio'],
            },
        ),
    ]
