# Generated by Django 6.0.5 on 2026-06-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_add_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagem do Evento'),
        ),
    ]
