# Generated by Django 6.0.5 on 2026-06-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_compromisso_apoiadores_compromisso_cabos_and_more'),
        ('mapa', '0005_delete_agendaaliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='aliados',
            field=models.ManyToManyField(blank=True, related_name='compromissos', to='mapa.aliadochapa', verbose_name='Aliados de chapa presentes'),
        ),
        migrations.AddField(
            model_name='evento',
            name='aliados',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='mapa.aliadochapa', verbose_name='Aliados de chapa presentes'),
        ),
    ]
