# Generated by Django 6.0.5 on 2026-06-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_compromisso_aliados_evento_aliados'),
        ('liderancas', '0017_migrar_dados_lideranca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisso',
            name='apoiadores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'papel': 'apoiador'}, related_name='compromissos_apoiador', to='liderancas.lideranca', verbose_name='Apoiadores participantes'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='cabos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'papel': 'cabo'}, related_name='compromissos_cabo', to='liderancas.lideranca', verbose_name='Cabos participantes'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='coordenadores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'papel': 'coordenador'}, related_name='compromissos_coordenador', to='liderancas.lideranca', verbose_name='Coordenadores participantes'),
        ),
    ]
