# Generated by Django 6.0.5 on 2026-07-02 17:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_compromisso_apoiadores_alter_compromisso_cabos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='eventos/anexos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'pdf'])], verbose_name='Arquivo')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_anexos', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='agenda.evento')),
            ],
            options={
                'verbose_name': 'Anexo do evento',
                'verbose_name_plural': 'Anexos do evento',
                'ordering': ['created_at'],
            },
        ),
    ]
