"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from importlib import import_module
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

SECRET_KEY = os.getenv('SECRET_KEY', 'insecure-dev-key-change-me')
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django.contrib.postgres',
    'core',
    'usuarios',
    'liderancas',
    'agenda',
    'pwa',
    'dashboard',
    'tarefas',
    'notificacoes',
    'mapa',
    'oportunidades',
]

AUTH_USER_MODEL = 'usuarios.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crm.middleware.RedirecionarUsuarioPWA',
]

ROOT_URLCONF = 'crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'liderancas.context_processors.leads_pendentes',
                'core.context_processors.campanha',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}

# O Postgres do Railway é servido atrás de um pooler (PgBouncer, transaction
# mode), onde SERVER-SIDE CURSORS quebram — e uma conexão persistente
# (conn_max_age) que falhe nesse ponto envenena os requests seguintes do mesmo
# worker. Desligar os cursores server-side torna todo QuerySet.iterator() um
# fetch client-side, seguro atrás do pooler. Trava para não reincidir o 500 do
# mapa/dashboard causado pelo .iterator() das Eleições 2022.
if DATABASES['default'].get('ENGINE') == 'django.db.backends.postgresql':
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = 'media/'
# Configurável por env para apontar a um volume persistente em produção
# (ex.: volume do Railway montado em /data/media). Em dev, disco local.
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', BASE_DIR / 'media'))

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Cache em memória do processo — usado pelo cache_page das APIs analíticas do
# mapa. Com múltiplos workers gunicorn cada worker tem o seu; para dados agregados
# isso é aceitável, pois o recompute de cada endpoint é enxuto (Eleições 2022 usa
# função de janela no banco: ~0,5s, ~0,2MB). NÃO usar DatabaseCache aqui: gravaria
# no volume do Postgres (já em ~86%) e não alivia recompute barato. Trocar por
# Redis só se precisar invalidação/compartilhamento entre workers.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
}

# Sessão em cache+banco: lê do cache (evita 1 SELECT em django_session por
# request — custo que pesa com o Postgres remoto/US-West) e persiste no banco,
# então não perde sessão ao reciclar o worker. Com 1 processo/N threads, o
# LocMemCache é compartilhado entre as threads.
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# ---- PWA: transcrição de áudio (Whisper) — opcional, ativa só se a chave existir ----
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
WHISPER_MODEL = os.environ.get('WHISPER_MODEL', 'whisper-1')
WHISPER_BASE_URL = os.environ.get('WHISPER_BASE_URL', 'https://api.openai.com/v1')

# ---- Limpeza de texto com IA (Claude) — opcional, ativa só se a chave existir ----
# Usada para corrigir/organizar o campo Observações (no PWA e na gestão das planilhas).
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
IA_LIMPEZA_MODEL = os.environ.get('IA_LIMPEZA_MODEL', 'claude-haiku-4-5')

# ---- Identidade da campanha (config de marca versionada — D10) ----
# MARCA=<slug> (env) seleciona configs/<slug>.py; config de marca é código
# versionado, não env — o env carrega só o seletor e os segredos. Toda referência
# a candidato/partido/número/cargo deve vir de settings.CAMPANHA (via o context
# processor `core.context_processors.campanha` nos templates). Não hardcodar
# marca no código.
MARCA = os.getenv('MARCA', 'isadora')
CAMPANHA = import_module(f'configs.{MARCA}').CAMPANHA

# Destino pós-login por marca. Isadora entra direto na Dashboard (Meta de Votos);
# demais marcas mantêm a capa de campanha em '/' (default acima).
LOGIN_REDIRECT_URL = CAMPANHA.get('LOGIN_REDIRECT_URL', LOGIN_REDIRECT_URL)
