# Generated by Django 6.0.5 on 2026-05-30 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0003_eleitor'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='liderancas.cidade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='convidado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convidados', to=settings.AUTH_USER_MODEL, verbose_name='Convidado por'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vinculo',
            field=models.CharField(blank=True, choices=[('coordenador', 'Coordenador'), ('cabo', 'Cabo Eleitoral'), ('replicador', 'Replicador')], max_length=20, verbose_name='Vínculo na rede'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Administrador'), ('coordenador', 'Coordenador'), ('lideranca', 'Liderança'), ('operador', 'Operador')], default='operador', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='secoes_permitidas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de seções da sidebar que o usuário pode acessar'),
        ),
    ]
