# Generated by Django 6.0.5 on 2026-05-31 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0005_delete_eleitor'),
        ('usuarios', '0002_alter_usuario_options_usuario_cidade_and_more'),
    ]

    operations = [
        # Step 1: Change CharField to nullable CharField (allows NULL)
        migrations.AlterField(
            model_name='usuario',
            name='regiao',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
    ]
