# Generated by Django 6.0.5 on 2026-05-31 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0005_delete_eleitor'),
        ('usuarios', '0003_alter_usuario_regiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='regiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='liderancas.regiao'),
        ),
    ]
