# Generated by Django 6.0.5 on 2026-06-02 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liderancas', '0007_add_endereco_voluntario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissaoResgate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('coordenador', 'Coordenador'), ('apoiador', 'Apoiador')], max_length=20, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da solicitação')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='doacoes/notas_fiscais/', verbose_name='Nota fiscal')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('apoiador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resgates_comissao', to='liderancas.apoiador', verbose_name='Apoiador')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resgates_comissao', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador')),
            ],
            options={
                'verbose_name': 'Resgate de Comissão',
                'verbose_name_plural': 'Resgates de Comissão',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doador_nome', models.CharField(max_length=200, verbose_name='Nome do doador')),
                ('doador_cpf', models.CharField(max_length=14, verbose_name='CPF do doador')),
                ('doador_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('doador_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateTimeField(verbose_name='Data da doação')),
                ('forma_pagamento', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão de Crédito'), ('transferencia', 'Transferência Bancária'), ('dinheiro', 'Dinheiro')], default='pix', max_length=20, verbose_name='Forma de pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('estornada', 'Estornada')], default='pendente', max_length=20, verbose_name='Status')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='doacoes/comprovantes/', verbose_name='Comprovante')),
                ('comissao_plataforma', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão plataforma (10%)')),
                ('comissao_coordenador', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão coordenador (7%)')),
                ('comissao_apoiador', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão apoiador (3%)')),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor líquido campanha (80%)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('apoiador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes', to='liderancas.apoiador', verbose_name='Apoiador responsável')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes', to='liderancas.cidade')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes_coordenadas', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador')),
                ('regiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes', to='liderancas.regiao')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-data'],
            },
        ),
    ]
