# Generated by Django 6.0.5 on 2026-06-27 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
        ('tarefas', '0010_alter_tarefa_cabos'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='tarefas.tarefa'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('mencao', 'Menção em comentário'), ('atribuicao', 'Atribuído como responsável'), ('participante', 'Adicionado como participante'), ('resposta', 'Resposta ao seu comentário'), ('prazo', 'Prazo próximo do vencimento'), ('lead_pwa', 'Novo lead do app')], max_length=20),
        ),
    ]
