# Generated by Django 6.0.5 on 2026-05-30 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Apoiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tipo', models.CharField(choices=[('politico', 'Apoiador Político'), ('empresarial', 'Apoiador Empresarial'), ('comunitario', 'Apoiador Comunitário'), ('associacao', 'Líder de Associação'), ('estrategico', 'Eleitor Estratégico'), ('imprensa', 'Imprensa')], max_length=20)),
                ('origem_contato', models.CharField(blank=True, max_length=200, verbose_name='Origem do Contato')),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10)),
                ('grau_influencia', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Médio'), ('baixo', 'Baixo')], default='medio', max_length=10, verbose_name='Grau de Influência')),
                ('frequencia_relacionamento', models.CharField(choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('eventual', 'Eventual')], default='mensal', max_length=15, verbose_name='Frequência de Relacionamento')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente')], default='ativo', max_length=10)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apoiadores_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apoiadores', to='liderancas.cidade')),
            ],
            options={
                'verbose_name': 'Apoiador',
                'verbose_name_plural': 'Apoiadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CoordenadorRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10)),
                ('frequencia_relacionamento', models.CharField(choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('eventual', 'Eventual')], default='mensal', max_length=15, verbose_name='Frequência de Relacionamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordenadores_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('cidade_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenadores', to='liderancas.cidade', verbose_name='Cidade Base')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenadores', to='liderancas.regiao')),
            ],
            options={
                'verbose_name': 'Coordenador Regional',
                'verbose_name_plural': 'Coordenadores Regionais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CaboEleitoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10)),
                ('frequencia_relacionamento', models.CharField(choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('eventual', 'Eventual')], default='mensal', max_length=15, verbose_name='Frequência de Relacionamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabos_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cabos_eleitorais', to='liderancas.cidade')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabos', to='liderancas.coordenadorregional')),
            ],
            options={
                'verbose_name': 'Cabo Eleitoral',
                'verbose_name_plural': 'Cabos Eleitorais',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='liderancas.regiao'),
        ),
    ]
