# Generated by Django 6.0.5 on 2026-05-30 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apoiador',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apoiadores_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caboeleitoral',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabos_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordenadorregional',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordenadores_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apoiador',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Prioridade Comunicação'),
        ),
        migrations.AlterField(
            model_name='caboeleitoral',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Prioridade Comunicação'),
        ),
        migrations.AlterField(
            model_name='coordenadorregional',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Prioridade Comunicação'),
        ),
    ]
