# Generated by Django 6.0.5 on 2026-05-30 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0002_apoiador_atualizado_por_caboeleitoral_atualizado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleitores_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleitores', to='liderancas.cidade')),
            ],
            options={
                'verbose_name': 'Eleitor',
                'verbose_name_plural': 'Eleitores',
                'ordering': ['-created_at'],
            },
        ),
    ]
