# Generated by Django 6.0.5 on 2026-05-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0003_eleitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoiador',
            name='tipo',
            field=models.CharField(choices=[('politico', 'Apoiador Político'), ('empresarial', 'Apoiador Empresarial'), ('comunitario', 'Apoiador Comunitário'), ('associacao', 'Líder de Associação'), ('estrategico', 'Eleitor Estratégico'), ('imprensa', 'Imprensa'), ('pwa', 'Apoiador PWA')], max_length=20),
        ),
    ]
