# Generated by Django 6.0.5 on 2026-05-31 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0004_alter_apoiador_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eleitor',
        ),
    ]
