# Generated by Django 6.0.5 on 2026-05-31 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0005_delete_eleitor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('disponibilidades', models.JSONField(blank=True, default=list, verbose_name='Disponibilidades')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntarios_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntarios', to='liderancas.cidade')),
                ('regiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntarios', to='liderancas.regiao')),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
                'ordering': ['-created_at'],
            },
        ),
    ]
