# Generated by Django 6.0.5 on 2026-06-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0006_voluntario'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereço'),
        ),
    ]
