# Generated by Django 6.0.5 on 2026-06-02 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0007_add_endereco_voluntario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroRegiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('populacao', models.IntegerField(default=0)),
                ('geojson', models.JSONField(blank=True, null=True)),
                ('cor', models.CharField(default='#3388ff', max_length=7)),
            ],
            options={
                'verbose_name': 'Macro Região',
                'verbose_name_plural': 'Macro Regiões',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='codigo_ibge',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='eleitores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cidade',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='meta_doacoes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cidade',
            name='meta_votos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cidade',
            name='num_vereadores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cidade',
            name='num_vereadores_pl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cidade',
            name='populacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cidade',
            name='prefeito_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cidade',
            name='prefeito_partido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cidade',
            name='presidente_pl',
            field=models.CharField(blank=True, max_length=200, verbose_name='Presidente Diretório PL'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='votos_sorgatto_2022',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cidade',
            name='zona_eleitoral',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='regiao',
            name='cor',
            field=models.CharField(default='#3388ff', max_length=7),
        ),
        migrations.AddField(
            model_name='regiao',
            name='eleitores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regiao',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regiao',
            name='meta_doacoes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='regiao',
            name='meta_votos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regiao',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='regiao',
            name='populacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regiao',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('slug', 'regiao')},
        ),
        migrations.AddField(
            model_name='regiao',
            name='macro_regiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regioes', to='liderancas.macroregiao'),
        ),
        migrations.CreateModel(
            name='ZonaEleitoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('eleitores', models.IntegerField(default=0)),
                ('local', models.CharField(blank=True, max_length=255)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_eleitorais', to='liderancas.cidade')),
            ],
            options={
                'verbose_name': 'Zona Eleitoral',
                'verbose_name_plural': 'Zonas Eleitorais',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('populacao', models.IntegerField(default=0)),
                ('geojson', models.JSONField(blank=True, null=True)),
                ('meta_votos', models.IntegerField(default=0)),
                ('meta_doacoes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros', to='liderancas.cidade')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'ordering': ['nome'],
                'unique_together': {('slug', 'cidade')},
            },
        ),
    ]
