# Generated by Django 6.0.5 on 2026-06-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0008_add_geography_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
