# Generated by Django 6.0.5 on 2026-06-06 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0010_soft_delete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteracaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação'), ('visita', 'Visita'), ('reuniao', 'Reunião'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('evento', 'Evento'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Interação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apoiador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='liderancas.apoiador')),
                ('cabo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='liderancas.caboeleitoral')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='liderancas.coordenadorregional')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'ordering': ['-data'],
            },
        ),
    ]
