# Generated by Django 6.0.5 on 2026-06-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0013_interacaolog_egresso_interacaolog_lassberg'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoiador',
            name='meta_votos_transferir',
            field=models.IntegerField(default=0, help_text='Quantos votos deste político a campanha quer transferir para o LS.', verbose_name='Meta de votos a transferir'),
        ),
        migrations.AddField(
            model_name='apoiador',
            name='votos_referencia',
            field=models.IntegerField(default=0, help_text='Votos que este político obteve na última eleição (base da máquina de voto).', verbose_name='Votos de referência'),
        ),
    ]
