# Generated by Django 6.0.5 on 2026-06-27 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0015_cidade_adversario_nome_cidade_adversario_partido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lideranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('papel', models.CharField(choices=[('coordenador', 'Coordenador Regional'), ('cabo', 'Cabo Eleitoral'), ('apoiador', 'Apoiador')], db_index=True, max_length=12)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Prioridade Comunicação')),
                ('frequencia_relacionamento', models.CharField(choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('eventual', 'Eventual')], default='mensal', max_length=15, verbose_name='Frequência de Relacionamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('tipo', models.CharField(blank=True, choices=[('politico', 'Apoiador Político'), ('empresarial', 'Apoiador Empresarial'), ('comunitario', 'Apoiador Comunitário'), ('associacao', 'Líder de Associação'), ('estrategico', 'Eleitor Estratégico'), ('imprensa', 'Imprensa'), ('pwa', 'Apoiador PWA')], max_length=20, verbose_name='Categoria do Apoiador')),
                ('cargo', models.CharField(blank=True, choices=[('prefeito', 'Prefeito'), ('vice_prefeito', 'Vice-Prefeito'), ('vereador', 'Vereador'), ('presidente_diretorio', 'Presidente Diretório'), ('ex_politico', 'Ex-Político'), ('outro', 'Outro')], max_length=25, verbose_name='Cargo Político')),
                ('votos_referencia', models.IntegerField(default=0, verbose_name='Votos de referência')),
                ('meta_votos_transferir', models.IntegerField(default=0, verbose_name='Meta de votos a transferir')),
                ('origem_contato', models.CharField(blank=True, max_length=200, verbose_name='Origem do Contato')),
                ('grau_influencia', models.CharField(blank=True, choices=[('alto', 'Alto'), ('medio', 'Médio'), ('baixo', 'Baixo')], max_length=10, verbose_name='Grau de Influência')),
                ('status', models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderancas_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderancas_cadastradas', to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liderancas', to='liderancas.cidade')),
                ('coordenador_responsavel', models.ForeignKey(blank=True, limit_choices_to={'papel': 'coordenador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderados', to='liderancas.lideranca', verbose_name='Coordenador Responsável')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('regiao', models.ForeignKey(blank=True, help_text='Usada pelo coordenador como área de atuação; nos demais, deriva da cidade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderancas', to='liderancas.regiao', verbose_name='Região de atuação')),
            ],
            options={
                'verbose_name': 'Liderança',
                'verbose_name_plural': 'Lideranças',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['papel', 'is_active'], name='liderancas__papel_42c6f6_idx')],
            },
        ),
    ]
