# Generated by Django 6.0.5 on 2026-06-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_compromisso_apoiadores_alter_compromisso_cabos_and_more'),
        ('liderancas', '0017_migrar_dados_lideranca'),
        # Deletar caboeleitoral só DEPOIS que tarefas/0010 re-apontou Tarefa.cabos
        # para lideranca — senão sobra referência pendurada ao deletar o modelo.
        ('tarefas', '0010_alter_tarefa_cabos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacaolog',
            name='apoiador',
        ),
        migrations.RemoveField(
            model_name='caboeleitoral',
            name='atualizado_por',
        ),
        migrations.RemoveField(
            model_name='caboeleitoral',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='caboeleitoral',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='caboeleitoral',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='caboeleitoral',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='interacaolog',
            name='cabo',
        ),
        migrations.RemoveField(
            model_name='coordenadorregional',
            name='atualizado_por',
        ),
        migrations.RemoveField(
            model_name='coordenadorregional',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='coordenadorregional',
            name='cidade_base',
        ),
        migrations.RemoveField(
            model_name='coordenadorregional',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='coordenadorregional',
            name='regiao',
        ),
        migrations.RemoveField(
            model_name='interacaolog',
            name='coordenador',
        ),
        migrations.AddField(
            model_name='interacaolog',
            name='lideranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='liderancas.lideranca'),
        ),
        migrations.DeleteModel(
            name='Apoiador',
        ),
        migrations.DeleteModel(
            name='CaboEleitoral',
        ),
        migrations.DeleteModel(
            name='CoordenadorRegional',
        ),
    ]
