# Generated by Django 6.0.5 on 2026-06-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0019_unaccent_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='lideranca',
            name='pwa_client_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='ID do cadastro PWA'),
        ),
    ]
