# Generated by Django 6.0.5 on 2026-06-27 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0020_lideranca_pwa_client_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lideranca',
            name='aprovacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], db_index=True, default='aprovado', max_length=10, verbose_name='Aprovação'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderancas_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, verbose_name='Motivo da rejeição'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='origem',
            field=models.CharField(choices=[('crm', 'CRM'), ('pwa', 'App PWA'), ('import', 'Importação')], default='crm', max_length=10),
        ),
    ]
