# Generated by Django 6.0.5 on 2026-06-28 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0021_lideranca_aprovacao_lideranca_aprovado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='aprovacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], db_index=True, default='aprovado', max_length=10, verbose_name='Aprovação'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntarios_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, verbose_name='Motivo da rejeição'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='origem',
            field=models.CharField(choices=[('crm', 'CRM'), ('pwa', 'App PWA'), ('import', 'Importação')], default='crm', max_length=10),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='pwa_client_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='ID do cadastro PWA'),
        ),
    ]
