# Generated by Django 6.0.5 on 2026-06-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0022_voluntario_aprovacao_voluntario_aprovado_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='num_vereadores_pl',
            new_name='num_vereadores_partido',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='votos_sorgatto_2022',
            new_name='votos_referencia_2022',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='presidente_pl',
            new_name='presidente_diretorio',
        ),
        migrations.AlterField(
            model_name='cidade',
            name='presidente_diretorio',
            field=models.CharField(blank=True, max_length=200, verbose_name='Presidente Diretório NOVO'),
        ),
    ]
