# Generated by Django 6.0.5 on 2026-06-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0023_rename_num_vereadores_pl_cidade_num_vereadores_partido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacaolog',
            name='egresso',
        ),
        migrations.RemoveField(
            model_name='lassberg',
            name='atualizado_por',
        ),
        migrations.RemoveField(
            model_name='lassberg',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='lassberg',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='lassberg',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='interacaolog',
            name='lassberg',
        ),
        migrations.DeleteModel(
            name='Egresso',
        ),
        migrations.DeleteModel(
            name='Lassberg',
        ),
    ]
