# Generated by Django 6.0.5 on 2026-07-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0024_remove_interacaolog_egresso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lideranca',
            name='atendente',
            field=models.CharField(blank=True, help_text='Quem fez/conduz o atendimento deste contato.', max_length=100, verbose_name='Atendente'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='canal_atendimento',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=12, verbose_name='Canal do último atendimento'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='contato_feito',
            field=models.BooleanField(default=False, verbose_name='Contato feito?'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='data_contato',
            field=models.DateField(blank=True, null=True, verbose_name='Data do contato'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='doou',
            field=models.BooleanField(default=False, verbose_name='Doou?'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereço (entrega de material)'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='filiado_partido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Filiado a algum partido?'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='intencao_voto',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('talvez', 'Talvez'), ('nao', 'Não'), ('nao_contactado', 'Não contactado')], max_length=15, verbose_name='Intenção de voto'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='material_entregue',
            field=models.BooleanField(default=False, verbose_name='Material entregue?'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='nivel',
            field=models.CharField(blank=True, choices=[('multiplicador', 'Multiplicador (líder)'), ('lead', 'Lead')], max_length=15, verbose_name='Nível'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='quem_e_eleitor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Quem é o eleitor?'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='segmentos',
            field=models.CharField(blank=True, max_length=255, verbose_name='Segmentos/Interesses'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='uf',
            field=models.CharField(blank=True, default='SC', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='vaquinha_enviada',
            field=models.BooleanField(default=False, verbose_name='Link da vaquinha enviado?'),
        ),
    ]
