# Generated by Django 6.0.5 on 2026-07-08 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0027_backfill_tipos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lideranca',
            name='atendente_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderancas_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Atendente (usuário)'),
        ),
        migrations.AlterField(
            model_name='lideranca',
            name='atendente',
            field=models.CharField(blank=True, help_text='Quem fez/conduz o atendimento deste contato (texto livre/legado/import).', max_length=100, verbose_name='Atendente'),
        ),
        migrations.AlterField(
            model_name='lideranca',
            name='canal_atendimento',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter')], max_length=12, verbose_name='Canal do último atendimento'),
        ),
        migrations.AlterField(
            model_name='lideranca',
            name='nivel',
            field=models.CharField(blank=True, choices=[('voluntario', 'Voluntário'), ('eleitor', 'Eleitor'), ('lead', 'Lead'), ('multiplicador', 'Multiplicador (líder)'), ('nd', 'N/d')], max_length=15, verbose_name='Nível'),
        ),
    ]
