# Generated by Django 6.0.5 on 2026-07-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0028_lideranca_atendente_user_alter_lideranca_atendente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lideranca',
            name='nivel',
            field=models.CharField(blank=True, choices=[('voluntario', 'Voluntário'), ('eleitor', 'Eleitor'), ('lead', 'Lead'), ('multiplicador', 'Multiplicador (líder)')], max_length=15, verbose_name='Nível'),
        ),
    ]
