# Generated by Django 6.0.5 on 2026-07-08 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0029_alter_lideranca_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lideranca',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liderancas', to='liderancas.cidade'),
        ),
    ]
