# Generated by Django 6.0.5 on 2026-07-10 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0032_migrar_nivel_lead_para_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='mesorregiao',
            field=models.ForeignKey(blank=True, limit_choices_to={'nivel': 'meso'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cidades_meso', to='liderancas.regiao', verbose_name='Mesorregião'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='microrregiao',
            field=models.ForeignKey(blank=True, limit_choices_to={'nivel': 'micro'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cidades_micro', to='liderancas.regiao', verbose_name='Microrregião'),
        ),
        migrations.AddField(
            model_name='regiao',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código IBGE da meso/microrregião (vazio para associações).', max_length=10, verbose_name='Código IBGE'),
        ),
        migrations.AddField(
            model_name='regiao',
            name='nivel',
            field=models.CharField(choices=[('associacao', 'Associação de Municípios'), ('micro', 'Microrregião'), ('meso', 'Mesorregião')], db_index=True, default='associacao', max_length=12, verbose_name='Nível'),
        ),
    ]
