# Generated by Django 6.0.5 on 2026-07-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0033_cidade_mesorregiao_cidade_microrregiao_regiao_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lideranca',
            name='formas_ajuda',
            field=models.JSONField(blank=True, default=list, help_text='Em que o apoiador quer ajudar (múltipla escolha).', verbose_name='Formas de ajuda'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='quer_trabalho_remunerado',
            field=models.BooleanField(default=False, verbose_name='Quer trabalhar (remunerado)'),
        ),
    ]
